version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: maadhar
      MYSQL_USER: root
      MYSQL_PASSWORD: master

  spring-app:
    image: myaadharappspringboot
    ports:
      - "9191:9191"
    depends_on:
      - mysql
